

DATA_OUTPUT_LOCATION = "./Data/Processed/"
MIDI_INPUT_LOCATION = "./Data/PreProcessed/Jazz/"
MIDI_OUTPUT_LOCATION = "./Midi Output/"
MODEL_LOCATION = "./Model/Saved/Conv Nets/"
PICKLE_FILE_NAME = "Jazz.obj"

TIME_OF_TIME_SLICE = .1
MAX_NOTE = 81
# MIN_NOTE = 61
MIN_NOTE = 33
NOTES_COUNT = MAX_NOTE - MIN_NOTE + 1
NEURAL_INPUT_SIZE = NOTES_COUNT
NOTE_ACTIVE_VALUE = 7

INPUT_SEQUENCE_LENGTH = 96
# OUTPUT_SEQUENCE_LENGTH = 50

CONV_KERNAL_HEIGHT = 5

VALIDATION_DATA_SPLIT = .05
LEARNING_RATE = 0.001
DECAY_RATE = 0.000001
BATCHES = 64
EPOCHS = 30
TRAINING_LOSS = 'categorical_crossentropy'
ACTIVATION = 'softmax'
LAYER_SIZE = 96
TRAINING_METRICS = ['accuracy']

NOTE_CUTOFF = .4